spring:
  application:
    name: leon-parser

leon:
  urlTemplate:
    get:
      sportsLeagues: https://leonbets.com/api-2/betline/sports?ctag=en-US&flags=urlv2
      matchByLeagueId: https://leonbets.com/api-2/betline/events/all?ctag=en-US&league_id=%s&hideClosed=true&flags=reg,urlv2,mm2,rrc,nodup
      marketByMatchId: https://leonbets.com/api-2/betline/event/all?ctag=en-US&eventId=%s&flags=reg,urlv2,mm2,rrc,nodup,smgv2,outv2


